### ISSUE TITLE
Refactor assertMessageForDate

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-release-bot#4]
## Background

When we need to pass more than 1 input to a function, consider passing an object (referred to as "named arguments" in Ember). A hash (POJO) helps remove order dependency and clarify the invocation site.

## Problem

The file `test/cron/daily-message.js` has a custom assertion called `assertMessageForDate`. Currently, it has 4 "positional arguments."

## TODOs

- [ ] Update the signature of `assertMessageForDate`.

    ```javascript
    // Before
    async function assertMessageForDate(today, releaseDate, message, released = []) { ... }

    // After
    async function assertMessageForDate({ todayDate, releaseDate, message, released = [] }) { ... }
    ```

- [ ] Update the invocations in `test/cron/daily-message.js`. For example,

   ```javascript
    // Before
    await assertMessageForDate('2020-07-13', '2020-07-20', 'Release week starts next week on 2020-07-20 are we all prepared? :lts:');

    // After
    await assertMessageForDate({
      todayDate: '2020-07-13',
      releaseDate: '2020-07-20',
      message: 'Release week starts next week on 2020-07-20 are we all prepared? :lts:',
    });
    ```

**Comment by ronan-f** [comment]
I'm happy to submit a PR for this

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue labelled with `Hacktoberfest` in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by ijlee2** [comment]
@ronan-f Thanks, I look forward to see your PR. Let us know if you have any questions!

**Comment by ronan-f** [comment]
PR added [here](https://github.com/ember-learn/ember-release-bot/pull/7)
